// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int num = Integer.parseInt(args[0]);
		double random = 0.0;
		int one = 0;
		int half = 0;
		double ratio = 0;

		for (int i=0; i < num; i++) {
			random = Math.random();
			if (random < 0.5){
				half++;
			}
			if (random > 0.5){
				one++;
			}
		}
			System.out.println("> 0.5:  " + half + " times");
			System.out.println("<= 0.5:  " + one + " times");

			if (half != 0 && one != 0){
				ratio =(double)one / half;
				System.out.println("Ratio:  " + ratio);
			}
			

	}
}
